### PR TITLE
global bio4j reorg

### PR DESCRIPTION
**Pull request by laughedelic**
I'm putting this here I don't know why. This is just the director's cut from ohnosequences/bio4j-paper#25

@laughedelic @pablopareja 
# bio4j changes
## github org repo layout
- [x] bio4j/bio4j ↦ the abstract model, incorporating the contents of what is now called **bio4j-model**. Also generic docs will go there; it will act as some sort of hub for the whole bio4j experience :)
- [x] bio4j/bio4j-titandb
- [x] bio4j/bio4j-neo4jdb
- [x] ohnosequences/bio4j-paper ↦ bio4j/???-paper once we submit it
- [x] ohnosequences/bio4j-scala ↦ bio4j/bio4j-modules
- [x] bio4j/bio4j.github.com
- [x] bio4j/Bio4jModel ↦ bio4j/DEPRECATED Bio4jModel and we add a link to the main bio4j/bio4j repo.
- [x] bio4j/Bio4jTools ↦ bio4j/examples
- [x] all the other stuff: add a big DEPRECATED to the name, link to the main repo.
### development and release process

Integrate all development into the standard sbt-based workflow. This means
- [x] using the release plugin
- [ ] writing proper release notes for the initial release (and keep doing it further on)
- [ ] fix those lingering "sbt stuff on windows" issues
### docs
- [ ] move things out of the wiki, into the main repository. 
- [ ] All docs should be included with repos, and correspond to the current branch
- [ ] update the website
- [x] add the new slides somewhere

### CODE REVIEW

**Comment by laughedelic** [comment]
I wanted to rename Bio4jTools, but I don't have permissions "/

**Comment by laughedelic** [comment]
I renamed the DEPRECATED repos and changed description. Two things:
- let's keep consistency: either `Bio4j` or `bio4j`, because `.../bio4j/Bio4j` looks not nice :-1: 
- I don't know why, but the repos names in https://github.com/bio4j don't update "/

**Comment by laughedelic** [comment]
I moved `ohnosequences/bio4j-paper` to `bio4j/bio4j-paper` and now I don't even see it (no permissions)

**Comment by laughedelic** [comment]
I have restructured the FOSDEM repository. Now our presentations are separated. So where should we put them? I guess mine can go to `bio4j/bio4j-modules` docs.

**Comment by laughedelic** [comment]
Added FOSDEM slides on the [website](http://ohnosequences.com/slides/fosdem-2014/)

**Comment by laughedelic** [comment]
@pablopareja
We should finish this today, so let's review what we haven't done yet:
- [ ] Move wikis to the repos' docs 
  - I think, I can do this — just moving things around..
- [ ] Update the website 
  - I don't know what to do here, so I guess it's more a task for @pablopareja, but if you need any help, tell me, what should I do

Also there are some questionable things:
- [ ] writing proper release notes for the initial release (and keep doing it further on)
  - this is more like a reminder for the future
- [ ] fix those lingering "sbt stuff on windows" issues 
  - @pablopareja, does everything work for you now? if no, tell me what needs to be fixed
- [ ] Moving the new slides somewhere
  - I added them to ohnoseq website, but I guess they should appear somehow on the bio4j website as well (may be a blogpost about FOSDEM?)

**Comment by laughedelic** [comment]
Hey @bio4j/coders guys,
I'm organising docs in the [`bio4j/examples`](https://github.com/bio4j/examples/tree/org/wiki-to-docs) repo and I want to move those per-program wiki pages to the code and then generate docs (+plus TOC with short descriptions). 
- WHYT? may be it's not worthy and then I will just put those wiki files in `docs/`.
- can we get rid of this ~~nonsense~~ copyright message in **every** source file and just add one `LICENSE` file in the root of the repo?

**Comment by laughedelic** [comment]
and also, what about moving to sbt there?

**Comment by laughedelic** [comment]
one more question to @pablopareja:
- there are files with the same name like `com/era7/bioinfo/bio4j/tools/gephi/ApplyLayoutAlgoAndFiltersToGexf` and `com/era7/bioinfo/bio4j/tools/ApplyLayoutAlgoAndFiltersToGexf` (one level up)
- they are not exactly the same, but almost
- are ~10 of such files
- why and what should I do with them?

**Comment by laughedelic** [comment]
@bio4j/coders any feedback here?

**Comment by eparejatobes** [comment]
tomorrow!

**Comment by pablopareja** [comment]
Hey!
- _**Website**_: I don't know what you want to do here, let me know if I need to do something specific about this
- _**SBT + Windows**_: I think everything works now but e.g. I didn't try to release most of the projects yet
- _**Slides**_: Should we then set the one from FOSDEM as the official one and replace [this one](http://www.slideshare.net/pablo_pareja/bio4j) ?
- _**License comments**_ These are not nonsense at all and they are supposed to be there, what's the harm in any case?
- _**Bio4jTools examples**_ I can have a look at all of them and update them to the new version

**Comment by laughedelic** [comment]
- _**Website**_: I don't know, but I think it's mostly about no activity in the blog and outdated info. @eparejatobes ?
- _**Slides**_: I think yes
- _**License comments**_ 
  - they are not in all files
  - I think that a one License file in the repo is more than enough
  - why to waste time scrolling 30 lines in every file? better to write a comment what's this code about :wink: 
  - I guess it's something, IDE pastes for you in every file, so you can just change your template
- _**Bio4jTools examples**_ ok, cool :+1:

**Comment by laughedelic** [comment]
/me
- [x] bio4j org logo: svg one
- [x] github-sbt `org/name` consistency:
  - `bio4j` sbt organization everywhere
  - names without `bio4j-` prefix
- [x] move `bio4j/bio4j` wiki to docs
- [x] split `bio4j/model` on
  - `bio4j/bio4j` containing abstract part
  - `bio4j/blueprints` with the rest
- [x] `bio4j/titandb` readme
- [x] `bio4j/modules` readme
- [x] ~~illusionary~~ repos for all modules:
  - ncbi-taxonomy-module
  - gi-taxonomy-index-module

@bio4j/coders tell me, if I forgot something

**Comment by laughedelic** [comment]
I tried to organize bio4j/ repos on huboard and aggregated everything in bio4j/bio4j: 
- https://huboard.com/bio4j/bio4j/

may be it will be useful for you too

**Comment by laughedelic** [comment]
I added a short readme for [bio4j/titandb](https://github.com/bio4j/titandb) and extended readme for the [bio4j/modules](https://github.com/bio4j/modules) repo. I also created repos for 4 modules and a template to generate the rest (tomorrow).

@pablopareja note, that readmes of the bio4j/model and bio4j/neo4jdb really need some love.

**Comment by laughedelic** [comment]
is anything happening here?

**Comment by eparejatobes** [comment]
should be done by now right?

**Comment by laughedelic** [comment]
but I don't think it is

**Comment by eparejatobes** [comment]
what's missing

**Comment by laughedelic** [comment]
I don't know

**Comment by pablopareja** [comment]
Should I do anything about this then?

**Comment by eparejatobes** [comment]
let's move this to bio4j/bio4j#14

**Comment by laughedelic** [comment]
As we moved this, let's merge it.

**Pull request merged**
