### PR TITLE
streaming xml parsers - options

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by eparejatobes** [comment]
We talked a bit about this in #24, I collected old links and stuff and this is what I got
- The API I was speaking about is [StAX](http://docs.oracle.com/javase/tutorial/jaxp/stax/why.html)
- the Jackson guys did this super-fast StAX-compliant parser: [aalto-xml](https://github.com/FasterXML/aalto-xml). It even has some rudimentary support for non-blocking parsing: [Non-blocking XML parsing Aalto 0.9.7](http://www.cowtowncoder.com/blog/archives/2011/03/entry_451.html)

This example from SO was helpful for me in understanding how all this things go together:
- [Loading local chunks in DOM while parsing a large XML file in SAX (Java)](https://stackoverflow.com/questions/7998733/loading-local-chunks-in-dom-while-parsing-a-large-xml-file-in-sax-java?)

**Comment by eparejatobes** [comment]
@bio4j/coders check this out

**Comment by laughedelic** [comment]
ultra-fast ultra-cool

**Comment by pablopareja** [comment]
OK my only concern is whether you can "go back" a few lines or "go up" a few levels to the ancestor tag once you find what you're interested in?

**Comment by eparejatobes** [comment]
@pablopareja  what's exactly the use case? I don't know if I understand you

**Comment by pablopareja** [comment]
yeah so let's say that you have the following simplified XML sample:

``` xml
        <protein accession="P132432">
            <references>
                <external-db source="RefSeq">
                    <lalalala/>
                </external-db>
            </references>
        </protein>
```

You would be looking for tags **external-db** only when the attribute **source** is equal to _**RefSeq**_ but once this happens the other value you need to know is the **protein accession**...

**Comment by evdokim** [comment]
I think that yoc can jsut always store this contex: path from root with all attributes

**Comment by eparejatobes** [comment]
well (obviously) that won't work as-is; you'd need to store the fragment over which you need to backtrack

**Comment by pablopareja** [comment]
So that's what I meant from the beginning that I don't see any possible way to make the best out of an event-based XML parsing when in order to know if you're interested in the grand-parent you need to check the grand-son and if that's the case then you need the information from both...

**Comment by eparejatobes** [comment]
but this will be essentially as efficient as possible; just stream through the file to locate the regions which you need to traverse, and some DOM-like XPATH thing for doing this traversal. For example
- http://andreas.haufler.info/2012/01/conveniently-processing-large-xml-files.html

**Comment by pablopareja** [comment]
Yeah, the thing's that the XML is pretty much just a flat list of entries...
Maybe I don't understand what you mean but unless there's some manual temporal storage of the last lines before an event is fired I don't see how you can get any benefits with this in this specific scenario

**Comment by eparejatobes** [comment]
could you post a link to the code that does this in some import program?

**Comment by pablopareja** [comment]
https://github.com/bio4j/bio4j-titandb/blob/master/src/main/java/com/ohnosequences/bio4j/titan/programs/ImportUniprotTitan.java#L161

**Comment by laughedelic** [comment]
moved to bio4j/bio4j#8

**Pull request merged**
