### PR TITLE
simplify project build - meeting

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by eparejatobes** [comment]
@evdokim @pablopareja @laughedelic @eparejatobes
- [x] get a list of repos for bio4j dependencies
- [x] clarify what else is needed to switch to the standard build and release process

**Comment by eparejatobes** [comment]
Java-only settings:
- [x] `autoScalaLibrary := false` for getting rid of the dep on the Scala library [sbt - configuring Scala](http://www.scala-sbt.org/release/docs/Detailed-Topics/Configuring-Scala.html)
- [x] `crossPaths := false` for the artifact name: [SO - How do you remove the _<scala-version> postfix from artifacts built+published with simple-build-tool?](http://stackoverflow.com/questions/8288859/how-do-you-remove-the-scala-version-postfix-from-artifacts-builtpublished-wi)
- [x] whatever we need from here: [sbt - Java sources](http://www.scala-sbt.org/release/docs/Detailed-Topics/Java-Sources)

cc ohnosequences/era7-sbt-release#2

**Comment by laughedelic** [comment]
@evdokim  @eparejatobes 
Please, guys, tell me what else is needed for java, so that I can do release asap: ohnosequences/era7-sbt-settings#2

**Comment by evdokim** [comment]
I use these settings:

``` scala
javacOptions ++= Seq("-source", "1.7", "-target", "1.7")

javacOptions ++= Seq("-encoding", "UTF-8")

publishArtifact in packageDoc := false
```

**Comment by laughedelic** [comment]
I like your approach with separating the same setting on two. Anyway, I'm adding this, what else?

I would also add `publishArtifact in (Compile, packageSrc) := false`...

**Comment by laughedelic** [comment]
And yes, are these `javacOptions` for everybody or only for java projects?

**Comment by laughedelic** [comment]
Ok, I guess, for everybody. Done.

**Comment by eparejatobes** [comment]
@laughedelic yep, I looked a bit into it and it seems that targeting 1.7 should be OK (as long as you _run_ it under 1.7 of course)

**Comment by laughedelic** [comment]
fine. what about sources publishing?

**Comment by eparejatobes** [comment]
honestly, I don't know. I guess that some IDE people like it

**Comment by laughedelic** [comment]
Ok. I'm not doing anything with sources.
ohnosequences/nice-sbt-settings#2

**Comment by eparejatobes** [comment]
closing?

**Comment by laughedelic** [comment]
looks like it was just about starting to use nice-sbt-settings. if so, then yes

**Comment by eparejatobes** [comment]
@evdokim ?

**Comment by evdokim** [comment]
yes, it can be closed

I have no idea what for this repo

**Pull request merged**
