### PR TITLE
Issues with GI index

### PR DESCRIPTION
**Pull request by laughedelic**
Any call like `Bio4jDistribution.GITaxonomyIndex.nodeRetriever.getNCBITaxonByGiId("...")` returns `null`.

`TODO:` check how this module is imported, may be there are some errors in logs. 

GIs for testing: https://s3-eu-west-1.amazonaws.com/resources.ohnosequences.com/taxapasta/nt.16S.fasta

### CODE REVIEW

**Comment by pablopareja** [comment]
Hey!

Sorry for the delay but I've been giving 100% priority to another project that had to be done these past few days.
You're right, I guess that in the end I simply forgot  to implement that method... :laughing: 
@laughedelic Let's have a short meeting this morning and we talk about it ?

**Comment by laughedelic** [comment]
Ok, let's meet ")

**Comment by laughedelic** [comment]
IT WORKZ!!!!!

**Pull request merged**
